import { GlobalProvider } from "@/context/global";
import "@/styles/globals.css";
import Head from 'next/head'; // Importa el componente Head

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
       <title>MyPokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <GlobalProvider>
        <Component {...pageProps} />
      </GlobalProvider>
    </>
  );
}
